version: '2'

services:
  adianta_flask:
    build: ./flask/.
    command: uwsgi --ini uwsgi.ini
    environment:
      PYTHONUNBUFFERED: 'True'
    ports:
      - '8080:8080'
    volumes:
      - .:/adianta_flask